- name: handler1
  copy:
    src: "{{item}}"
    dest: /var/www/html/
  loop: "{{ files }}"
  changed_when: true
  notify: handler2

- name: handler2
  ansible.builtin.sysvinit:
    name: nginx
    state: restarted