- name: Install nginx 
  ansible.builtin.apt:
    name: nginx
    state: present
  changed_when: true
  notify: handler1

- name: Template a file to /etc/file.conf
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  changed_when: true
  notify: handler2

  